<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="6" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-20T17:26:54 IST" name="Suite" finished-at="2022-04-20T17:27:10 IST" duration-ms="15742">
    <groups>
      <group name="smoke">
        <method signature="IndexPageTest.verifyLogo()[pri:2, instance:com.myA1store.testcases.IndexPageTest@5524cca1]" name="verifyLogo" class="com.myA1store.testcases.IndexPageTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2022-04-20T17:26:54 IST" name="Test" finished-at="2022-04-20T17:27:10 IST" duration-ms="15742">
      <class name="com.myA1store.testcases.IndexPageTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.myA1store.testcases.IndexPageTest@5524cca1]" started-at="2022-04-20T17:26:54 IST" name="setup" finished-at="2022-04-20T17:27:08 IST" duration-ms="14375" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogo()[pri:2, instance:com.myA1store.testcases.IndexPageTest@5524cca1]" started-at="2022-04-20T17:27:08 IST" name="verifyLogo" finished-at="2022-04-20T17:27:08 IST" duration-ms="130" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.myA1store.testcases.IndexPageTest.verifyLogo(IndexPageTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogo -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.myA1store.testcases.IndexPageTest@5524cca1]" started-at="2022-04-20T17:27:09 IST" name="teardown" finished-at="2022-04-20T17:27:10 IST" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.myA1store.testcases.IndexPageTest -->
      <class name="com.myA1store.testcases.LoginPageTest">
        <test-method is-config="true" signature="extentRep()[pri:0, instance:com.myA1store.testcases.LoginPageTest@5b218417]" started-at="2022-04-20T17:26:54 IST" name="extentRep" finished-at="2022-04-20T17:26:54 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentRep -->
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.myA1store.testcases.LoginPageTest@5b218417]" started-at="2022-04-20T17:26:54 IST" name="loadConfig" finished-at="2022-04-20T17:26:54 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="afterSuit()[pri:0, instance:com.myA1store.testcases.LoginPageTest@5b218417]" started-at="2022-04-20T17:27:10 IST" name="afterSuit" finished-at="2022-04-20T17:27:10 IST" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- com.myA1store.testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
